name: "Release"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "ESLint"
        uses: gimenete/eslint-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build"
        run: npm run build

      - name: "Upload"
        uses: actions/upload-artifact@master
        with:
          name: gdata-provider.xpi
          path: dist/gdata-provider.xpi
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Download Build Artifact"
        uses: actions/download-artifact@master
        with:
          name: gdata-provider.xpi
          path: dist

      - name: "Run Tests"
        uses: kewisch/action-thunderbird-tests@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          channel: nightly
          xpcshell: test/xpcshell/xpcshell.ini
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Download Build Artifact"
        uses: actions/download-artifact@master
        with:
          name: gdata-provider.xpi
          path: dist

      - name: "Generate changelog"
        run: |
          npm install conventional-changelog
          ./node_modules/.bin/conventional-changelog -p angular -r 2 | tee dist/CHANGELOG.md

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: dist/gdata-provider.xpi
          channel: listed
          apiUrlPrefix: "https://addons.thunderbird.net/api/v3"
          apiKey: ${{ secrets.ATN_SIGN_KEY }}
          apiSecret: ${{ secrets.ATN_SIGN_SECRET }}

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/gdata-provider.xpi
          body_path: dist/CHANGELOG.md
